### ISSUE TITLE
No response

### ISSUE THREAD

**Issue by vvalvesga** [OpenReqEU/analytics-backend#2]
Hi, 

I had follow steps and I have not response when I call services.

By example: 
I run analytics-backend in port 30000 and it's open in my machine.
`docker run -d -p 30000:80 analytics-backend`
But when I call getUmatrix service, by example, it's not work
`ip:30000/getUmatrix?som_model_id=1`

**Comment by claudiareng** [comment]
@vvalvesga  could you please tell me which type of error you receive?

**Comment by vvalvesga** [comment]
With postman:

```
Could not get any response
There was an error connecting to ip:30000/getUmatrix?som_model_id=1.
Why this might have happened:
The server couldn't send a response:
Ensure that the backend is working properly
Self-signed SSL certificates are being blocked:
Fix this by turning off 'SSL certificate verification' in Settings > General
Proxy configured incorrectly
Ensure that proxy is configured correctly in Settings > Proxy
Request timeout:
Change request timeout in Settings > General
```

If I remove the port I get: 
```
<HTML>
    <HEAD>
        <TITLE>404 Not Found</TITLE>
    </HEAD>
    <BODY>
        <H1>404 Not Found</H1>
The requested URL was not found
    </BODY>
</HTML>
```

**Comment by claudiareng** [comment]
@vvalvesga the correct URL should be ip:30000/analytics-backend/getUmatrix?som_model_id=1. Can you try whith this?

**Comment by vvalvesga** [comment]
It still doesn't work.

**Comment by claudiareng** [comment]
Which is the response now?

**Comment by vvalvesga** [comment]
Same

**Comment by vvalvesga** [comment]
It works for me!!!

I launch this command:
`docker logs -f 5c94fb53c9fa`



```
WARNING -   Theano Import Error
 * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
2019-03-20 11:16:14,673 : INFO :  * Running on http://0.0.0.0:10601/ (Press CTRL+C to quit)
```

And launch the container with that port
`docker run -d -p 10601:10601 analytics-backend`

Request: 
`x.x.x.x:10601/analytics-backend/getCostOfSom?som_model_id=1
`And it works

**Comment by claudiareng** [comment]
Perfect!
